name: Rakit APK Kasir Voice Clean

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Ambil Kode dari Repositori
      uses: actions/checkout@v3

    - name: Pasang Java Environment Modern
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Pasang Flutter SDK Versi Terbaru
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Ambil Library dan Bersihkan Cache V1
      run: |
        flutter clean
        flutter pub get

    - name: Masak File APK Rilis Final
      run: flutter build apk --release --no-tree-shake-icons

    - name: Simpan Berkas Hasil Jadi APK
      uses: actions/upload-artifact@v3
      with:
        name: Kasir-Voice-Apk-Final
        path: build/app/outputs/flutter-apk/app-release.apk
