name: Rakit APK Kasir Voice Clean

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode dari Repositori GitHub
        uses: actions/checkout@v4

      - name: Set up Java SDK Modern untuk Android
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Pasang Flutter SDK Versi Stabil Terbaru
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Paksa Lahirkan Struktur Folder Android Stabil
        run: flutter create --platforms=android .

      - name: Bersihkan Cache dan Unduh Library Modern
        run: |
          flutter clean
          flutter pub get

      - name: Proses Memasak Paket APK Rilis
        run: flutter build apk --release --no-tree-shake-icons

      - name: Simpan dan Upload Hasil Jadi Berkas APK v4
        uses: actions/upload-artifact@v4
        with:
          name: Kasir-Voice-Apk-Final
          path: build/app/outputs/flutter-apk/app-release.apk
